### ISSUE TITLE
Merge to MGEMod?

### ISSUE THREAD

**Issue by walliski** [ChillyPunch/ChillyMGE#4]
Hey

Just wondered how much this plugin is modified on top of the original MGE one? It would be easier for us server admins if we could use the same plugin for all maps, and have links to all maps from the MGE repo :thinking: So could it be possible to merge these changes into the MGE repo instead of having them separate?

//Walliski

**Comment by pepperkick** [comment]
Hey there,

This map should work fine with old version of the map upto some extent, and vice versa is also true, all the old maps should work fine with the this plugin but again upto some extent. The reason I had to modify the plugin for this map was due to the limitations that the original plugin had, only 32 areas were maximum allowed for mge which was not suitable for this map, alongside this I added some features which enhanced the map due to which I didn't make a PR in original mge repo cause the map was specifically made in that way to compliment the modified plugin, so lot of the features won't work in other maps. Also the features are not completely bug free either.

Hopefully that explains why I kept the plugin separate then original.

As I was a server admin myself I can understand the frustration but one solution I can think of is to use the mapconfig plugin to switch between original and modified plugin.
